function nEstadisticos =  nivelesEstadisticosPonderadosC(parent,BGC,LC)

nEstadisticos.mainC = parent;

uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.02 0.5 0.09 0.1],...
                                'String','LCImáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.10 0.5 0.09 0.1],...
                                'String','LCImin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');  
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.18 0.5 0.09 0.1],...
                                'String','LCFmáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.26 0.5 0.09 0.1],...
                                'String','LCFmin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');    
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.34 0.5 0.09 0.1],...
                                'String','LCSmáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.42 0.5 0.09 0.1],...
                                'String','LCSmin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                                
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.5 0.5 0.09 0.1],...
                                'String','LCeq', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.58 0.5 0.09 0.1],...
                                'String','LC01', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.66 0.5 0.09 0.1],...
                                'String','LC10', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.74 0.5 0.09 0.1],...
                                'String','LC50', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.82 0.5 0.09 0.1],...
                                'String','LC90', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');
uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.9 0.5 0.09 0.1],...
                                'String','LC99', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');        
                            
nEstadisticos.txLICmax = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.02 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLICmin = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.1 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLFCmax = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.18 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLFCmin = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.26 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLSCmax = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.34 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLSCmin = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.42 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLeqC  = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.5 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            

nEstadisticos.txL01C  = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.58 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL10C  = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.66 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL50C  = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.74 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL90C  = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.82 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL99C  = uicontrol('Parent', nEstadisticos.mainC,'Style', 'text','unit','normalized', 'Position', [0.9 0.4 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
                            
end