function nEstadisticos =  nivelesEstadisticosPonderadosA(parent,BGC,LC)

nEstadisticos.mainA = parent;


uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.02 0.8 0.09 0.1],...
                                'String','LAImáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.10 0.8 0.09 0.1],...
                                'String','LAImin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');  
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.18 0.8 0.09 0.1],...
                                'String','LAFmáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.26 0.8 0.09 0.1],...
                                'String','LAFmin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');    
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.34 0.8 0.09 0.1],...
                                'String','LASmáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.42 0.8 0.09 0.1],...
                                'String','LASmin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                                
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.5 0.8 0.09 0.1],...
                                'String','LAeq', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.58 0.8 0.09 0.1],...
                                'String','LA01', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.66 0.8 0.09 0.1],...
                                'String','LA10', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.74 0.8 0.09 0.1],...
                                'String','LA50', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.82 0.8 0.09 0.1],...
                                'String','LA90', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');
uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.9 0.8 0.09 0.1],...
                                'String','LA99', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');        
                            
nEstadisticos.txLIAmax = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.02 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);   
nEstadisticos.txLIAmin = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.1 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLFAmax = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.18 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLFAmin = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.26 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLSAmax = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.34 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLSAmin = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.42 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txLeqA  = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.5 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL01A  = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.58 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL10A  = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.66 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL50A  = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.74 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL90A  = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.82 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
nEstadisticos.txL99A  = uicontrol('Parent', nEstadisticos.mainA,'Style', 'text','unit','normalized', 'Position', [0.9 0.7 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                            
                            
end