function nEstadisticos =  nivelesEstadisticosPonderadosZ(parent,BGC,LC)

nEstadisticos.mainZ = parent;

uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.02 0.2 0.09 0.1],...
                                'String','LZImáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.10 0.2 0.09 0.1],...
                                'String','LZImin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');  
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.18 0.2 0.09 0.1],...
                                'String','LZFmáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.26 0.2 0.09 0.1],...
                                'String','LZFmin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');    
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.34 0.2 0.09 0.1],...
                                'String','LZSmáx', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.42 0.2 0.09 0.1],...
                                'String','LZSmin', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                                
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.5 0.2 0.09 0.1],...
                                'String','LZeq', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.58 0.2 0.09 0.1],...
                                'String','LZ01', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.66 0.2 0.09 0.1],...
                                'String','LZ10', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.74 0.2 0.09 0.1],...
                                'String','LZ50', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                            
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.82 0.2 0.09 0.1],...
                                'String','LZ90', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');
uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.9 0.2 0.09 0.1],...
                                'String','LZ99', 'FontSize', 12,'BackgroundColor',BGC,'ForegroundColor',LC,'FontWeight','bold');                             
                         
                            %% -- texto de tiempo estadistio max Instantaneo
                         
nEstadisticos.txLIZmax = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.02 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);  
                            % -- texto de tiempo estadistio min Instantaneo
nEstadisticos.txLIZmin = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.1 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);   
                            % -- texto de tiempo estadistio max Fast
nEstadisticos.txLFZmax = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.18 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);  
                            % -- texto de tiempo estadistio min Fast
nEstadisticos.txLFZmin = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.26 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);  
                            % -- texto de tiempo estadistio max Slow
nEstadisticos.txLSZmax = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.34 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);  
                            % -- texto de tiempo estadistio min Slow
nEstadisticos.txLSZmin = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.42 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC); 
                            
                            %% ---------------------------%%
                            % -- texto de tiempo estadistio Leq
nEstadisticos.txLeqZ  = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.5 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC); 
                            % -- texto de tiempo estadistio L01
nEstadisticos.txL01Z  = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.58 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);                             
                            % -- texto de tiempo estadistio L10
nEstadisticos.txL10Z  = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.66 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);  
                            % -- texto de tiempo estadistio L50
nEstadisticos.txL50Z  = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.74 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);   
                            % -- texto de tiempo estadistio L90
nEstadisticos.txL90Z  = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.82 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC); 
                            % -- texto de tiempo estadistio L99
nEstadisticos.txL99Z  = uicontrol('Parent', nEstadisticos.mainZ,'Style', 'text','unit','normalized', 'Position', [0.9 0.1 0.09 0.1],...
                                'String','-Inf', 'FontSize', 9,'BackgroundColor',BGC,'ForegroundColor',LC);
                            


end